In [1]:
!pip install transformers

     |████████████████████████████████| 3.1 MB 17.1 MB/s 
     |████████████████████████████████| 59 kB 4.2 MB/s 
     |████████████████████████████████| 3.3 MB 26.0 MB/s 
     |████████████████████████████████| 596 kB 14.1 MB/s 
     |████████████████████████████████| 895 kB 25.2 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
!pip install datasets

     |████████████████████████████████| 290 kB 27.8 MB/s 
     |████████████████████████████████| 1.1 MB 44.2 MB/s 
     |████████████████████████████████| 132 kB 58.0 MB/s 
     |████████████████████████████████| 243 kB 44.3 MB/s 
     |████████████████████████████████| 160 kB 57.6 MB/s 
     |████████████████████████████████| 192 kB 57.3 MB/s 
     |████████████████████████████████| 271 kB 43.7 MB/s 


In [3]:
import transformers
#import datasets

In [4]:
from transformers import pipeline
classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)


Downloading:   0%|          | 0.00/629 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/255M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

In [ ]:
 classifier('Why the hell do we need to always work in english?')

[{'label': 'NEGATIVE', 'score': 0.9997010827064514}]

In [ ]:
 classifier('It is a good time to start a business')

[{'label': 'POSITIVE', 'score': 0.999862551689148}]

In [ ]:
 classifier('I did my homework')

[{'label': 'POSITIVE', 'score': 0.985089123249054}]

In [ ]:
anonimo = pipeline('sentiment-analysis', model="tr3cks/2LabelsSentimentAnalysisSpanish")

Downloading:   0%|          | 0.00/526 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/419M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/258 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/267k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
positivo=["Todos los profesores son unos ángeles. Gracias por tanto","intento estar tranquilo en momentos dificiles. Nada como una michelada y un ceviche",
          "actitud positiva!!",
          "Hoy es un dia muy feliz porque estoy aprediendo nuevos conceptos con estas ponencias",
          "la clase está muy interesante"]
negativo=["todos los políticos son unos corruptos" ,"A veces ni se cómo es que después de este año sigo vivo",
          "Solo sé que nada sé",
          "esta situación es poco agradable",
          "Hoy me fue mal en el trabajo :("]
varios=["Estoy en esa y le saqué un yogurt a mi sobrinito, lo estoy disfrutando con culpa","el cambio empieza en ti"]
neutros=["hola","adiós","El alfarero habló de su trabajo", "Hagamos nuestro el mundo"]

In [ ]:
anonimo(positivo)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': 'LABEL_1', 'score': 0.9998434782028198},
 {'label': 'LABEL_1', 'score': 0.989385187625885},
 {'label': 'LABEL_1', 'score': 0.9998871088027954},
 {'label': 'LABEL_1', 'score': 0.9998757839202881},
 {'label': 'LABEL_1', 'score': 0.9998615980148315}]

In [ ]:
anonimo(negativo)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': 'LABEL_0', 'score': 0.9998475313186646},
 {'label': 'LABEL_1', 'score': 0.9604994058609009},
 {'label': 'LABEL_0', 'score': 0.9980549812316895},
 {'label': 'LABEL_0', 'score': 0.9998443126678467},
 {'label': 'LABEL_0', 'score': 0.9998372793197632}]

In [ ]:
anonimo(varios)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': 'LABEL_1', 'score': 0.99015873670578},
 {'label': 'LABEL_1', 'score': 0.7236186265945435}]

In [ ]:
anonimo(neutros)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': 'LABEL_1', 'score': 0.9926964044570923},
 {'label': 'LABEL_0', 'score': 0.770512044429779},
 {'label': 'LABEL_1', 'score': 0.9997654557228088},
 {'label': 'LABEL_1', 'score': 0.9998241066932678}]

In [5]:
bert_español = pipeline('sentiment-analysis', model="nlptown/bert-base-multilingual-uncased-sentiment")

Downloading:   0%|          | 0.00/953 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/638M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/851k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
bert_español(positivo)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': '5 stars', 'score': 0.5416908264160156},
 {'label': '2 stars', 'score': 0.37163451313972473},
 {'label': '5 stars', 'score': 0.4692154824733734},
 {'label': '5 stars', 'score': 0.6852555871009827},
 {'label': '4 stars', 'score': 0.48274141550064087}]

In [ ]:
bert_español(negativo)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': '1 star', 'score': 0.6841946840286255},
 {'label': '3 stars', 'score': 0.28943851590156555},
 {'label': '1 star', 'score': 0.3430871367454529},
 {'label': '2 stars', 'score': 0.5511030554771423},
 {'label': '2 stars', 'score': 0.4360464811325073}]

In [ ]:
bert_español(neutros)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': '3 stars', 'score': 0.25504201650619507},
 {'label': '5 stars', 'score': 0.43525686860084534},
 {'label': '4 stars', 'score': 0.35986682772636414},
 {'label': '5 stars', 'score': 0.6405256986618042}]

In [ ]:
bert_español(varios)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': '1 star', 'score': 0.4330402612686157},
 {'label': '5 stars', 'score': 0.23197485506534576}]

In [ ]:
sintaxis=["Eran un buen amiga", 
          "Juana se despertó en la mañana radiante",
          "Juana, radiante, se despertó en la mañana", 
          "Era una mañana radiante. Juana se despertó"]
anonimo(sintaxis)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': 'LABEL_1', 'score': 0.9996739625930786},
 {'label': 'LABEL_1', 'score': 0.9991797804832458},
 {'label': 'LABEL_1', 'score': 0.9993854761123657},
 {'label': 'LABEL_1', 'score': 0.9985440969467163}]

In [ ]:
bert_español(sintaxis)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': '4 stars', 'score': 0.38153621554374695},
 {'label': '1 star', 'score': 0.42343154549598694},
 {'label': '1 star', 'score': 0.2743496596813202},
 {'label': '1 star', 'score': 0.4494759440422058}]

In [ ]:
composicional=["el perro se comió la cena de mi hermano", 
               "mi hermano se comió la cena del perro",
               "Fue consumida la comida de mi hermano por el perro", 
               "uno se comió la cena del otro"]
anonimo(composicional)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': 'LABEL_0', 'score': 0.9997983574867249},
 {'label': 'LABEL_0', 'score': 0.9997085928916931},
 {'label': 'LABEL_0', 'score': 0.9998337030410767},
 {'label': 'LABEL_0', 'score': 0.99945467710495}]

In [ ]:
bert_español(composicional)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': '1 star', 'score': 0.2604069709777832},
 {'label': '5 stars', 'score': 0.2895061671733856},
 {'label': '1 star', 'score': 0.537451446056366},
 {'label': '1 star', 'score': 0.4661582410335541}]

In [ ]:
conocimiento=["la experiencia fue larga","la noche entre los dos fue larga","la fila del banco fue larga"]
anonimo(conocimiento)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': 'LABEL_1', 'score': 0.9993669390678406},
 {'label': 'LABEL_0', 'score': 0.9942891597747803},
 {'label': 'LABEL_1', 'score': 0.5357869267463684}]

In [ ]:
bert_español(conocimiento)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': '3 stars', 'score': 0.3084324896335602},
 {'label': '2 stars', 'score': 0.3988797068595886},
 {'label': '2 stars', 'score': 0.40602150559425354}]

In [ ]:
polisemia=["era muy ligera", "la cámara era muy ligera", "la película era muy ligera"]
anonimo(polisemia)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': 'LABEL_0', 'score': 0.7445540428161621},
 {'label': 'LABEL_0', 'score': 0.9807511568069458},
 {'label': 'LABEL_0', 'score': 0.9851417541503906}]

In [ ]:
bert_español(polisemia)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': '2 stars', 'score': 0.3181767463684082},
 {'label': '2 stars', 'score': 0.3792048692703247},
 {'label': '2 stars', 'score': 0.3407782316207886}]

In [ ]:
anafora=["hacia rato no recibía uno de estos",
         "Recibí un puño. Hacia rato no recibía uno de estos" , 
         "Recibí un regalo. Hacia rato no recibía uno de estos"]
anonimo(anafora)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': 'LABEL_0', 'score': 0.9997355341911316},
 {'label': 'LABEL_0', 'score': 0.9993575215339661},
 {'label': 'LABEL_1', 'score': 0.9978360533714294}]

In [ ]:
bert_español(anafora)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': '1 star', 'score': 0.6497987508773804},
 {'label': '1 star', 'score': 0.743328869342804},
 {'label': '1 star', 'score': 0.6056778430938721}]

In [ ]:
pragmatica=["La batería es perfecta para ahorrar pues alcanza para una sola llamada",
            "Todos los políticos del país son unos ángeles", 
            "qué malo haber recibido tanta plata por mi trabajo"]
anonimo(pragmatica)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': 'LABEL_1', 'score': 0.9997838139533997},
 {'label': 'LABEL_0', 'score': 0.9716970324516296},
 {'label': 'LABEL_0', 'score': 0.9118944406509399}]

In [ ]:
bert_español(pragmatica)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


[{'label': '5 stars', 'score': 0.6421208381652832},
 {'label': '5 stars', 'score': 0.32244712114334106},
 {'label': '1 star', 'score': 0.7030344605445862}]

In [6]:
from google.colab import files
uploaded = files.upload()

Saving tass14neg.txt to tass14neg.txt
Saving tass14pos.txt to tass14pos.txt


In [7]:
positivo=[]
with open("tass14pos.txt", encoding="latin-1") as f:
    for line in f:
        positivo.append(line)
len(positivo)

negativo=[]
with open("tass14neg.txt", encoding="latin-1") as f:
    for line in f:
        negativo.append(line)
len(negativo)

total=positivo + negativo
len(total)


4300

In [8]:
respuesta=[1]*len(positivo)+ [0]*len(negativo)
len(respuesta)


4300

##Pasos de trabajo
Con una muestra, vamos a explicar un poco el proceso realizado por un transformer. Primero sacamos la muestra.

In [12]:
import random
tassprueba=random.sample(positivo,100)+random.sample(negativo,100)


Luego mostraremos las etapas: tokenización, generación de representación y adaptación a la tarea

In [17]:
from transformers import AutoTokenizer
modelo="dccuchile/bert-base-spanish-wwm-cased"
modelo2="nlptown/bert-base-multilingual-uncased-sentiment"
tokenizado = AutoTokenizer.from_pretrained(modelo)

Downloading:   0%|          | 0.00/364 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/236k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/469k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/134 [00:00<?, ?B/s]

Ahora tokenicemos. Miremos que hace el tokenizador

In [18]:
verlotok=tokenizado.tokenize("Esta es la prueba definitiva de lo mucho que te quiero")
print(verlotok)

['Esta', 'es', 'la', 'prueba', 'definitiva', 'de', 'lo', 'mucho', 'que', 'te', 'quiero']


In [19]:
vernum=tokenizado.convert_tokens_to_ids(verlotok)
print(vernum)

[1949, 1058, 1030, 3889, 8988, 1008, 1114, 1789, 1038, 1240, 1937]


Ahora tokenizamos y convertimos nuestros tokenes a tensores (matrices de números). También creamos la capa de atención.
Obsérvese que tenemos que reemplazar con tokenes vacíos cuando las longitudes son diferentes (padding) y evitar que sean más largas de lo que el transformer puede aguantar (truncation)

In [20]:
entradas = tokenizado(tassprueba, padding=True, truncation=True, return_tensors="tf")
print(entradas)

{'input_ids': <tf.Tensor: shape=(200, 108), dtype=int32, numpy=
array([[    4,  1198, 26989, ...,     1,     1,     1],
       [    4,  4189, 16324, ...,     1,     1,     1],
       [    4, 19832,   977, ...,     1,     1,     1],
       ...,
       [    4, 21050, 10136, ...,     1,     1,     1],
       [    4,  4894,  1084, ...,     1,     1,     1],
       [    4,  1162,  8640, ...,     1,     1,     1]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(200, 108), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(200, 108), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32

Ahora cargamos el modelo. Modelo no está hecho para predecir sentimiento, por eso nos va a fallar, pero luego vamos a sintonizarlo en fino.

In [15]:
from transformers import TFAutoModel

model = TFAutoModel.from_pretrained(modelo)

Downloading:   0%|          | 0.00/648 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/512M [00:00<?, ?B/s]

Some layers from the model checkpoint at dccuchile/bert-base-spanish-wwm-cased were not used when initializing TFBertModel: ['mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFBertModel were not initialized from the model checkpoint at dccuchile/bert-base-spanish-wwm-cased and are newly initialized: ['bert/pooler/dense/bias:0', 'bert/pooler/dense/kernel:0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Veamos el tamaño de nuestros tensores en la salida de nuestro modelo. Nos está entregando las capas ocultas (la representación)

In [21]:
salida=model(entradas)
print(salida.last_hidden_state.shape)

(200, 108, 768)


Ahora importamos el modelo como si fuese para clasificar

In [22]:
from transformers import TFAutoModelForSequenceClassification

modelsentiment = TFAutoModelForSequenceClassification.from_pretrained(modelo)
salidasent = modelsentiment(entradas)

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at dccuchile/bert-base-spanish-wwm-cased and are newly initialized: ['classifier', 'bert/pooler/dense/bias:0', 'bert/pooler/dense/kernel:0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Ahora si, solo tenemos los logits

In [23]:
print(salidasent.logits.shape)

(200, 2)


In [24]:
print(salidasent.logits)

tf.Tensor(
[[-3.65570188e-03 -8.35297257e-02]
 [-4.37367968e-02 -6.50478154e-03]
 [ 3.77766415e-02  6.10721335e-02]
 [ 1.00570634e-01  5.85951991e-02]
 [ 7.29518011e-03 -4.84840423e-02]
 [ 4.92780879e-02  1.89099684e-02]
 [-1.49562716e-01 -1.29840896e-02]
 [ 3.95826176e-02  7.07842931e-02]
 [ 3.27329747e-02 -1.21621788e-03]
 [-6.13331646e-02  4.10448760e-02]
 [-1.42758816e-01  1.25617534e-02]
 [ 4.00230512e-02 -1.19386658e-01]
 [-7.49714673e-02  6.64665624e-02]
 [-2.21200157e-02  2.44114175e-02]
 [-3.71793136e-02  1.83875337e-02]
 [ 2.09258199e-02  3.54254469e-02]
 [ 1.40193552e-01 -7.49009699e-02]
 [ 3.90750766e-02  2.28136554e-02]
 [-5.24031073e-02 -6.32113665e-02]
 [-3.27883661e-02  3.85246389e-02]
 [ 9.78367031e-03  4.76866961e-04]
 [-8.71563628e-02  8.63066837e-02]
 [ 1.87468976e-02  1.00452185e-01]
 [-1.30505748e-02  2.13407725e-02]
 [-1.72836334e-03 -1.05437741e-01]
 [ 6.99532181e-02  8.14059079e-02]
 [ 4.87486683e-02 -2.27746964e-02]
 [ 1.11424267e-01  8.18471760e-02]
 [-1.3039

Como no hay etiquetas configuradas, el las marca como 0 y 1.

In [25]:
modelsentiment.config.id2label

{0: 'LABEL_0', 1: 'LABEL_1'}

Aqui entonces las volvemos probabilidades

In [26]:
import tensorflow as tf

prediccionproceso = tf.math.softmax(salidasent.logits, axis=-1)
print(prediccionproceso)

tf.Tensor(
[[0.5199579  0.4800421 ]
 [0.49069303 0.5093069 ]
 [0.49417636 0.5058236 ]
 [0.5104923  0.4895077 ]
 [0.5139412  0.48605883]
 [0.5075914  0.49240854]
 [0.46590832 0.53409165]
 [0.49220023 0.5077998 ]
 [0.50848645 0.4915135 ]
 [0.47442785 0.5255722 ]
 [0.4612477  0.53875226]
 [0.5397683  0.46023178]
 [0.46469933 0.5353007 ]
 [0.48836923 0.5116308 ]
 [0.48611185 0.5138881 ]
 [0.49637517 0.50362486]
 [0.5535673  0.44643277]
 [0.5040653  0.49593475]
 [0.50270206 0.49729797]
 [0.48217928 0.5178207 ]
 [0.50232667 0.4976733 ]
 [0.45674264 0.54325736]
 [0.47958502 0.52041495]
 [0.49140304 0.508597  ]
 [0.5259041  0.47409585]
 [0.49713683 0.5028631 ]
 [0.5178732  0.4821268 ]
 [0.5073937  0.49260628]
 [0.46114597 0.53885406]
 [0.50343776 0.4965623 ]
 [0.5419886  0.45801142]
 [0.5058107  0.49418932]
 [0.48855937 0.51144063]
 [0.52754086 0.47245917]
 [0.45815656 0.5418435 ]
 [0.5003823  0.49961764]
 [0.4961719  0.5038281 ]
 [0.48765913 0.51234084]
 [0.5258344  0.47416562]
 [0.48836744 0

In [27]:
type(prediccionproceso)

tensorflow.python.framework.ops.EagerTensor

##Sintonizado fino de modelos
Ahora vamos a hacer la sintonización fina de un modelo de lenguaje natural a nuestra tarea de análisis de sentimiento. Empezamos por crear el dataset

Aqui creamos el dataset

In [28]:
import pandas as pd
d = {'texto':total,'label':respuesta}
textobase=pd.DataFrame(d)
textobase.head(5)


texto  label
0                        @marodriguezb Gracias MAR\n      1
1  Conozco a alguien q es adicto al drama! Ja ja ...      1
2  Toca @crackoviadeTV3 . Grabación dl especial N...      1
3  Buen día todos! Lo primero mandar un abrazo gr...      1
4  Desde el escaño. Todo listo para empezar #endi...      1

In [42]:
textobase["label"].value_counts()

1    2709
0    1591
Name: label, dtype: int64

Primero con Pandas separamos la base de test. Luego, con ayuda de la librería datasets dividimos el entrenamiento en train y validation. Cmo vemos se convierte en un tipo de objetos Diccionario de datasets

In [29]:
from sklearn.model_selection import train_test_split
textobase_tr, textobase_test = train_test_split(textobase, test_size=0.05, random_state=42, stratify=respuesta)

In [30]:
from datasets import Dataset
basetot=Dataset.from_pandas(textobase_tr)
nuevo=basetot.train_test_split(test_size=0.2)
nuevo["train"].features

{'__index_level_0__': Value(dtype='int64', id=None),
 'label': Value(dtype='int64', id=None),
 'texto': Value(dtype='string', id=None)}

In [31]:
nuevo["test"].features

{'__index_level_0__': Value(dtype='int64', id=None),
 'label': Value(dtype='int64', id=None),
 'texto': Value(dtype='string', id=None)}

In [32]:
nuevo

DatasetDict({
    train: Dataset({
        features: ['texto', 'label', '__index_level_0__'],
        num_rows: 3268
    })
    test: Dataset({
        features: ['texto', 'label', '__index_level_0__'],
        num_rows: 817
    })
})

In [33]:
basetot.features

{'__index_level_0__': Value(dtype='int64', id=None),
 'label': Value(dtype='int64', id=None),
 'texto': Value(dtype='string', id=None)}

In [34]:
from transformers import AutoModel, AutoTokenizer, BertTokenizer,AutoModelForSequenceClassification

Creamos los tensores de nuestro modelo, haciendo el padding.

In [35]:
tokenizado2=AutoTokenizer.from_pretrained(modelo, padding=True, return_tensors="tf")


Creamos una función para el truncado

In [36]:
def tokenize_nuevo(base):
    return tokenizado2(base["texto"], truncation=True)

Y la ejecutamos

In [37]:
nuevo_tokenizado=nuevo.map(tokenize_nuevo, batched=True,)

  0%|          | 0/4 [00:00<?, ?ba/s]

  0%|          | 0/1 [00:00<?, ?ba/s]

Y ya aquí creamos los datasets de tensorflow que nos servirán para el entrenamiento

In [44]:
tensores_train= nuevo_tokenizado["train"].to_tf_dataset(
    columns=["attention_mask", "input_ids", "token_type_ids"],
    label_cols=["label"],
    shuffle=True,
     batch_size=32)

tensores_test= nuevo_tokenizado["test"].to_tf_dataset(
    columns=["attention_mask", "input_ids", "token_type_ids"],
    label_cols=["label"],
    shuffle=True,
     batch_size=32)

In [72]:
tensores_test

<PrefetchDataset shapes: ({attention_mask: (32, None), input_ids: (32, None), token_type_ids: (32, None)}, (32,)), types: ({attention_mask: tf.int64, input_ids: tf.int64, token_type_ids: tf.int64}, tf.int64)>

Cargamos el modelo como uno de clasificación

In [45]:
from transformers import TFAutoModelForSequenceClassification
from transformers import TFAutoModelForCausalLM


modelado = TFAutoModelForSequenceClassification.from_pretrained(modelo, num_labels=2)

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at dccuchile/bert-base-spanish-wwm-cased and are newly initialized: ['classifier', 'bert/pooler/dense/bias:0', 'bert/pooler/dense/kernel:0']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Y finalmente lo entrenamos de acuerdo a lo que necesitemos. 

In [46]:
class_weight = {0: 3.,
                1: 2.}

In [47]:
from tensorflow.keras.losses import SparseCategoricalCrossentropy

modelado.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=5e-5),
    loss=SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)
modelado.fit(
    tensores_train,
    validation_data=tensores_test,class_weight=class_weight
)

102/102 [==============================] - 3449s 34s/step - loss: 1.3803 - accuracy: 0.7059 - val_loss: 0.5318 - val_accuracy: 0.7500


In [49]:
predicciones = modelado.predict(tensores_test)["logits"]


In [51]:
display(predicciones)

array([[-0.9857655 ,  1.2106272 ],
       [-0.49818602,  0.710643  ],
       [ 0.12088899, -0.01653264],
       ...,
       [-0.16424346,  0.2235637 ],
       [-0.23815614,  0.30663204],
       [ 1.4339411 , -0.8268182 ]], dtype=float32)

In [52]:
import numpy as np
clase_predicha = np.argmax(predicciones, axis=1)
print(predicciones.shape, clase_predicha.shape)

(800, 2) (800,)


In [53]:
clase_predicha

array([1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,

In [62]:
import sklearn
from sklearn.metrics import precision_recall_curve, roc_curve, balanced_accuracy_score, f1_score, precision_score,recall_score, roc_auc_score



Aqui al final al parecer 17 tuits no tuvieron representación. Por eso toca recortar a 800

In [85]:
transprec=sklearn.metrics.precision_score(nuevo["test"]["label"][0:800],clase_predicha)
transrecall=sklearn.metrics.recall_score(nuevo["test"]["label"][0:800],clase_predicha)
transfscore=sklearn.metrics.f1_score(nuevo["test"]["label"][0:800],clase_predicha)
transauc=sklearn.metrics.roc_auc_score(nuevo["test"]["label"][0:800],clase_predicha)
print(transprec,transrecall,transfscore,transauc)

0.6247933884297521 0.7636363636363637 0.6872727272727273 0.5096870342771982
